logging:
  pattern:
    console: "[Kafka Pattern] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 8085

spring:
  application:
    name: kafka-stream-sample

  main:
    banner-mode: off
    log-startup-info: false

  kafka:
    bootstrap-servers:
      - localhost:9092

    listener:
      missing-topics-fatal: false

    consumer:
      group-id: kafka-stream-cg
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        compression.type: gzip

        spring.json.trusted.packages: com.jane.kafka.broker.message

        spring.json.value.default.type: java.lang.Object

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        compression.type: gzip

    streams:
      application-id: kafka-stream-sample-${random.uuid}

      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde

        spring.json.trusted.packages: com.jane.kafka.broker.message

        commit.interval.ms: 3000

        processing.guarantee: at_least_once